//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindWeaveServer.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchReports
    {
        public int report_id { get; set; }
        public int reporter_player_id { get; set; }
        public int reported_player_id { get; set; }
        public int match_id { get; set; }
        public System.DateTime report_time { get; set; }
    
        public virtual Matches Matches { get; set; }
        public virtual Player Player { get; set; }
        public virtual Player Player1 { get; set; }
    }
}
