//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindWeaveServer.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MindWeaveServer.Resources.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu código de recuperación es:.
        /// </summary>
        public static string EmailCodeInfoPasswordRecovery {
            get {
                return ResourceManager.GetString("EmailCodeInfoPasswordRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este código expirará en {0} minutos..
        /// </summary>
        public static string EmailExpiryInfo {
            get {
                return ResourceManager.GetString("EmailExpiryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Hola {0}!.
        /// </summary>
        public static string EmailGreeting {
            get {
                return ResourceManager.GetString("EmailGreeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si no solicitaste esto, puedes ignorar este correo de forma segura..
        /// </summary>
        public static string EmailIgnoreInfo {
            get {
                return ResourceManager.GetString("EmailIgnoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitaste restablecer tu contraseña para Mind Weave..
        /// </summary>
        public static string EmailInstructionPasswordRecovery {
            get {
                return ResourceManager.GetString("EmailInstructionPasswordRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gracias por registrarte. Usa el siguiente código para activar tu cuenta:.
        /// </summary>
        public static string EmailInstructionVerify {
            get {
                return ResourceManager.GetString("EmailInstructionVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recuperación de Contraseña - Mind Weave.
        /// </summary>
        public static string EmailSubjectPasswordRecovery {
            get {
                return ResourceManager.GetString("EmailSubjectPasswordRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de Verificación - Mind Weave.
        /// </summary>
        public static string EmailSubjectVerification {
            get {
                return ResourceManager.GetString("EmailSubjectVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Bienvenido a Mind Weave, {0}!.
        /// </summary>
        public static string EmailWelcome {
            get {
                return ResourceManager.GetString("EmailWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró una cuenta asociada a esos datos..
        /// </summary>
        public static string ErrorAccountNotFound {
            get {
                return ResourceManager.GetString("ErrorAccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todos los campos son requeridos..
        /// </summary>
        public static string ErrorAllFieldsRequired {
            get {
                return ResourceManager.GetString("ErrorAllFieldsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La ruta del avatar no puede estar vacía..
        /// </summary>
        public static string ErrorAvatarPathCannotBeEmpty {
            get {
                return ResourceManager.GetString("ErrorAvatarPathCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error inesperado al actualizar la ruta del avatar..
        /// </summary>
        public static string ErrorAvatarUpdateFailed {
            get {
                return ResourceManager.GetString("ErrorAvatarUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugador no encontrado..
        /// </summary>
        public static string ErrorPlayerNotFound {
            get {
                return ResourceManager.GetString("ErrorPlayerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Usuario no esta en línea.
        /// </summary>
        public static string ErrorUserNotOnline {
            get {
                return ResourceManager.GetString("ErrorUserNotOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error inesperado en el servidor..
        /// </summary>
        public static string GenericServerError {
            get {
                return ResourceManager.GetString("GenericServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu contraseña ha sido restablecida correctamente. Ya puedes iniciar sesión..
        /// </summary>
        public static string InfoPasswordResetSuccess {
            get {
                return ResourceManager.GetString("InfoPasswordResetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha enviado un código de recuperación a tu correo electrónico..
        /// </summary>
        public static string InfoRecoveryCodeSent {
            get {
                return ResourceManager.GetString("InfoRecoveryCodeSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu cuenta no ha sido verificada. Revisa tu correo.
        /// </summary>
        public static string LoginAccountNotVerified {
            get {
                return ResourceManager.GetString("LoginAccountNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El email o la contraseña son incorrectos..
        /// </summary>
        public static string LoginPasswordNotEmpty {
            get {
                return ResourceManager.GetString("LoginPasswordNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sesión iniciada..
        /// </summary>
        public static string LoginSuccessful {
            get {
                return ResourceManager.GetString("LoginSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro exitoso. Se ha enviado un código de verificación a tu correo electrónico..
        /// </summary>
        public static string RegistrationSuccessful {
            get {
                return ResourceManager.GetString("RegistrationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de usuario o el correo electrónico ya están en uso..
        /// </summary>
        public static string RegistrationUsernameOrEmailExists {
            get {
                return ResourceManager.GetString("RegistrationUsernameOrEmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Avatar actualizado correctamente..
        /// </summary>
        public static string SuccessAvatarUpdated {
            get {
                return ResourceManager.GetString("SuccessAvatarUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes tener al menos 13 años para registrarte..
        /// </summary>
        public static string ValidationDateOfBirthMinimumAge {
            get {
                return ResourceManager.GetString("ValidationDateOfBirthMinimumAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha de nacimiento no parece realista..
        /// </summary>
        public static string ValidationDateOfBirthRealistic {
            get {
                return ResourceManager.GetString("ValidationDateOfBirthRealistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha de nacimiento es obligatoria.
        /// </summary>
        public static string ValidationDateOfBirthRequired {
            get {
                return ResourceManager.GetString("ValidationDateOfBirthRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El formato del correo electrónico no es válido..
        /// </summary>
        public static string ValidationEmailFormat {
            get {
                return ResourceManager.GetString("ValidationEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo electrónico es obligatorio..
        /// </summary>
        public static string ValidationEmailRequired {
            get {
                return ResourceManager.GetString("ValidationEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre no puede exceder los 45 caracteres..
        /// </summary>
        public static string ValidationFirstNameLength {
            get {
                return ResourceManager.GetString("ValidationFirstNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre es obligatorio..
        /// </summary>
        public static string ValidationFirstNameRequired {
            get {
                return ResourceManager.GetString("ValidationFirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El apellido no puede exceder los 45 caracteres..
        /// </summary>
        public static string ValidationLastNameLength {
            get {
                return ResourceManager.GetString("ValidationLastNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo no puede comenzar ni terminar con espacios..
        /// </summary>
        public static string ValidationNoLeadingOrTrailingWhitespace {
            get {
                return ResourceManager.GetString("ValidationNoLeadingOrTrailingWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este campo solo puede contener letras..
        /// </summary>
        public static string ValidationOnlyLetters {
            get {
                return ResourceManager.GetString("ValidationOnlyLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe incluir al menos una mayúscula, una minúscula y un número.
        /// </summary>
        public static string ValidationPasswordComplexity {
            get {
                return ResourceManager.GetString("ValidationPasswordComplexity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe tener al menos 8 caracteres..
        /// </summary>
        public static string ValidationPasswordLength {
            get {
                return ResourceManager.GetString("ValidationPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña no puede contener espacios..
        /// </summary>
        public static string ValidationPasswordNoSpaces {
            get {
                return ResourceManager.GetString("ValidationPasswordNoSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña no puede estar vacía.
        /// </summary>
        public static string ValidationPasswordRequired {
            get {
                return ResourceManager.GetString("ValidationPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El perfil de usuario y la contraseña son obligatorios..
        /// </summary>
        public static string ValidationProfileOrPasswordRequired {
            get {
                return ResourceManager.GetString("ValidationProfileOrPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de usuario solo puede contener letras y números..
        /// </summary>
        public static string ValidationUsernameAlphanumeric {
            get {
                return ResourceManager.GetString("ValidationUsernameAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de usuario debe tener entre 3 y 16 caracteres.
        /// </summary>
        public static string ValidationUsernameLength {
            get {
                return ResourceManager.GetString("ValidationUsernameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de usuario no puede estar vacío..
        /// </summary>
        public static string ValidationUsernameRequired {
            get {
                return ResourceManager.GetString("ValidationUsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta cuenta ya ha sido verificada..
        /// </summary>
        public static string VerificationAccountAlreadyVerified {
            get {
                return ResourceManager.GetString("VerificationAccountAlreadyVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código de verificación solo debe contener 6 números..
        /// </summary>
        public static string VerificationCodeInvalidFormat {
            get {
                return ResourceManager.GetString("VerificationCodeInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo electrónico y el código son obligatorios..
        /// </summary>
        public static string VerificationEmailAndCodeRequired {
            get {
                return ResourceManager.GetString("VerificationEmailAndCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró una verificación pendiente para este correo..
        /// </summary>
        public static string VerificationEmailNotFound {
            get {
                return ResourceManager.GetString("VerificationEmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de verificación inválido o expirado..
        /// </summary>
        public static string VerificationInvalidOrExpiredCode {
            get {
                return ResourceManager.GetString("VerificationInvalidOrExpiredCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta verificada correctamente. Ya puedes iniciar sesión..
        /// </summary>
        public static string VerificationSuccessful {
            get {
                return ResourceManager.GetString("VerificationSuccessful", resourceCulture);
            }
        }
    }
}
